# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3970c3ca3297da4ce1cc7e44f031dd0397600cf80f6db92a92d954bd29f343ffe9b3ea8c2d822e9068a5a2d8bad0ae737e396cc4e9a7e874aa5d5f5c7c6c03b

test:
  secret_key_base: 8ea2e0b821a18bbeb2180bbf5b00aa4b25a8471b1664d3be29913e297a18cb697e39b663014af0218e44bfd4bfb5bd6a3bf73bd8516fb57a7f9e717c9ddd6f1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
